Classes init
DylanPKing/DnDCharacterManager pull request #5
Opened 2021-03-15 11:59 UTC by Bmalone100

I have implemented some foundations for classes.

2021-03-20 12:33 UTC, DylanPKing requested changes
Decent start, but needs some fixes. You should probably merge in from master to get the correct Armour types

2021-03-20 12:33 UTC, DylanPKing commented on .idea/misc.xml
> +  </component>
This doesn't need to be here

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/Proficient.java
> +    private String armour = "";
Should be the correct type.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/Proficient.java
> +    private ArrayList<String> weapons = new ArrayList<>();
Do we need both of these? Should Also be correct type.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/cleric/Cleric.java
> +    private HitDice hitdie = new HitDice();
camelCase

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/cleric/Cleric.java
> +    private String armour = "";
As said above, type. Also, shouldn't this be in the base class instead of repeated in every subclass?

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/fighter/Fighter.java
> +    private String armour = "";
Same as above.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/rogue/Rogue.java
> +    private String armour = "";
And here.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/wizard/Wizard.java
> +    private String armour = "";
And here.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/DnDClass.java
> +    private int health;
This looks good. Louise needs to add a class name attribute as well for the spells.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/cleric/Cleric.java
> +    private int health;
This is in the superclass, it doesn't need to be redeclared.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/cleric/Cleric.java
> +        health = hitdie.initHealth(hitdie.getHitDie());
This should be in the superclass constructor, and there should be a call to super here instead.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/fighter/Fighter.java
> +    private int health;
Same as above for health.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/fighter/Fighter.java
> +        health = hitdie.initHealth(hitdie.getHitDie());
Same as above for health.

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/rogue/Rogue.java
> +    private int health;
Superclass

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/rogue/Rogue.java
> +        health = hitdie.initHealth(hitdie.getHitDie());
Superclass

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/wizard/Wizard.java
> +    private int health;
Superclass

2021-03-20 12:33 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/wizard/Wizard.java
> +        health = hitdie.initHealth(hitdie.getHitDie());
Superclass

2021-03-21 10:51 UTC, Bmalone100 commented on src/main/java/com/seventhtill/dndclass/Proficient.java
> +    private String armour = "";
Added extends armor to Proficient and corrected my spelling from armour to armor. 
Updated getter and setter.

2021-03-21 11:10 UTC, Bmalone100 commented on src/main/java/com/seventhtill/dndclass/Proficient.java
> +    private ArrayList<String> weapons = new ArrayList<>();
We'll need to discuss where to implement Armor and Weapons since we can only extend one class at a time

2021-03-21 11:14 UTC, Bmalone100 commented on src/main/java/com/seventhtill/dndclass/cleric/Cleric.java
> +    private String armour = "";
I'll need assistance with that implementation.

2021-03-22 15:06 UTC, SzymonSztyrmer approved these changes
Other than that weird xml stuff looks workable

2021-03-22 15:06 UTC, SzymonSztyrmer commented on src/main/java/com/seventhtill/dndclass/ClericFactory.java
> +                "LIFE DOMAIN CLERIC")) {
I would recommend keeping those as one word strings. Not a blocker just an observation

2021-03-22 16:32 UTC, DylanPKing requested changes
Major overhaul, I like it! Very happy with this. Just some minor changes needed for whitespace like @SzymonSztyrmer mentioned, and a question about an import.

2021-03-22 16:32 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/ClericFactory.java
> +                "LIFE DOMAIN CLERIC")) {
Agreed. It's much easier to preemptively strip whitespace and set all to upper case from input than it is to try and fix the backend to work with input later.

2021-03-22 16:32 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/DnDClass.java
> +import javax.crypto.AEADBadTagException;
What's this for? Accidental import?

2021-03-22 16:32 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/FighterFactory.java
> +                "CHAMPION FIGHTER")) {
Same as above for Szymons comment. Just flagging for visibility.

2021-03-22 16:32 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/RogueFactory.java
> +                "THIEF ROGUE")) {
Same here for whitespace. Flagging for visibility.

2021-03-22 16:32 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/WizardFactory.java
> +                "EVOCATION WIZARD")) {
Same here for whitespace. Flagging for visibility.

2021-03-23 10:02 UTC, Bmalone100 commented on src/main/java/com/seventhtill/dndclass/ClericFactory.java
> +                "LIFE DOMAIN CLERIC")) {
I will change that then :)

2021-03-23 10:03 UTC, Bmalone100 commented on src/main/java/com/seventhtill/dndclass/DnDClass.java
> +import javax.crypto.AEADBadTagException;
Yes that occurred when I was typing a variable and alt entered when it switched to some system variable XD

2021-03-23 10:13 UTC, DylanPKing approved these changes
Looks great! Armour will need some slight retooling to work with the composite pattern but that can easily be done later.

2021-03-23 10:17 UTC, merged