Created a base for the ui using the command pattern
DylanPKing/DnDCharacterManager pull request #7
Opened 2021-03-22 14:02 UTC by SzymonSztyrmer

PR has base ui implementation with no functionality.
Set up using the command pattern.
More functionality will be added soon

2021-03-22 14:08 UTC, Bmalone100 approved these changes
Tactful validation as always XD

2021-03-23 13:36 UTC, SzymonSztyrmer reviewed
This update moves the cli into its own package along with the command
Sets up a ui for the character creation(name, race and class)
Things on this branch are dependent on chief's stuff to work
Weapon and armour is yet to be added.
Will like refactor the validation to shorten the code base.

2021-03-23 13:52 UTC, LouiseMadden requested changes
Just one little thing but otherwise looks good to me, need to fix the standard human in Cli.java

2021-03-23 13:52 UTC, LouiseMadden commented on src/main/java/com/seventhtill/ui/Cli.java
> +                characterRace = raceFactory.getRace("highelf");
Shouldn't this be standard human?

2021-03-23 13:57 UTC, SzymonSztyrmer commented on src/main/java/com/seventhtill/ui/Cli.java
> +                characterRace = raceFactory.getRace("highelf");
oh ya
that's a copy/paste blunder will fix

2021-03-23 16:10 UTC, SzymonSztyrmer reviewed
Big boi refactor to throw out duplicated code

2021-03-23 16:12 UTC, DylanPKing approved these changes

2021-03-24 13:06 UTC, LouiseMadden approved these changes
LGTM

2021-03-24 13:17 UTC, merged