Character Builder basic structure defined
DylanPKing/DnDCharacterManager pull request #8
Opened 2021-03-22 15:45 UTC by Bmalone100

placeholder strings in place for components.

Basic builder assembly defined.

2021-03-22 15:56 UTC, SzymonSztyrmer requested changes

2021-03-22 15:56 UTC, SzymonSztyrmer commented on src/main/java/com/seventhtill/characterSheet/CharacterSheet.java
> +        character.setCharacterItems("Rugsack of goods");
This really shouldnt be hardcoded. You need to make the builder adjustable so that we can create something other than a human cleric with a rugsack of goods

2021-03-22 16:15 UTC, DylanPKing requested changes
Solid start! Agree with @SzymonSztyrmer , but don't know enough about builder to offer more concrete feedback or guidance, unfortunately.

2021-03-22 16:15 UTC, DylanPKing commented on src/main/java/com/seventhtill/characterSheet/CharacterSheet.java
> +        character.setCharacterItems("Rugsack of goods");
Agreed. Either that or make multiple more explicit builders.

2021-03-23 11:29 UTC, LouiseMadden commented on src/main/java/com/seventhtill/characterSheet/Character.java
> +    public void setCharacterRace(Race race) { characterRace = race; }
extra whitespace in the body compared to the previous method

2021-03-23 11:29 UTC, LouiseMadden commented on src/main/java/com/seventhtill/characterSheet/Character.java
> +    public void setCharacterClass(DnDClass aClass) { characterClass= aClass; }
Same as above, also missing whitespace before =

2021-03-23 11:30 UTC, LouiseMadden commented on src/main/java/com/seventhtill/characterSheet/Character.java
> +    public void setCharacterItems(Item item) { characterItem = item; }
same as above, whitespace

2021-03-23 11:30 UTC, DylanPKing approved these changes
Looking good!

2021-03-23 11:30 UTC, LouiseMadden commented on src/main/java/com/seventhtill/characterSheet/Character.java
> +    public void setCharacterWeapon(Weapon weapon) { characterWeapon = weapon; }
Same as above whitespace

2021-03-23 11:33 UTC, LouiseMadden approved these changes
LGTM a few comments just on the layout of Character.java but other wise looks good

2021-03-23 11:33 UTC, LouiseMadden commented on src/main/java/com/seventhtill/characterSheet/Character.java
> +    public void setCharacterArmour(Armour armour) { characterArmour = armour; }
Same as above, whitespace

2021-03-23 11:33 UTC, LouiseMadden commented on src/main/java/com/seventhtill/characterSheet/Character.java
> +    public void setCharacterName(String name) {characterName = name; }
Should probably put the body on a new line, just for easier reading and consistency

2021-03-23 12:34 UTC, SzymonSztyrmer approved these changes
LGTM

2021-03-23 12:58 UTC, DylanPKing requested changes
Looks good, just need to fix some indentation.

2021-03-23 12:58 UTC, DylanPKing commented on src/main/java/com/seventhtill/Main.java
> +        import java.util.List;
Why are all these indented?

2021-03-23 12:58 UTC, DylanPKing commented on src/main/java/com/seventhtill/dndclass/rogue/ThiefRogue.java
> +private String name;
Should be indented.

2021-03-24 12:57 UTC, DylanPKing approved these changes

2021-03-24 13:01 UTC, merged